export default {
  "combo1":  "res/audios/combo1.mp3",
  "combo2":  "res/audios/combo2.mp3",
  "combo3":  "res/audios/combo3.mp3",
  "combo4":  "res/audios/combo4.mp3",
  "combo5":  "res/audios/combo5.mp3",
  "combo6":  "res/audios/combo6.mp3",
  "combo7":  "res/audios/combo7.mp3",
  "combo8":  "res/audios/combo8.mp3",
  "fall":  "res/audios/fall.mp3",
  "fall_2":  "res/audios/fall_2.mp3",
  "icon":  "res/audios/icon.mp3",
  "perfect":  "res/audios/perfect.mp3",
  "pop":  "res/audios/pop.mp3",
  "scale_intro":  "res/audios/scale_intro.mp3",
  "scale_loop":  "res/audios/scale_loop.mp3",
  "sing":  "res/audios/sing.mp3",
  "start":  "res/audios/start.mp3",
  "store":  "res/audios/store.mp3",
  "success":  "res/audios/success.mp3",
  "water":  "res/audios/water.mp3",
}